name: Lint, build, tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: lint:check
        run: |
          npm ci
      - name: build:build
        run: npm run build
      - name: test:check
        run: npm run test
